site_name: ZVISION的Wiki文档
site_description: 技术文档知识库
site_author: Administrator

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换亮色模式
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search:
      lang: zh

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 快速上手:
      - zvision_nz_series/quickstart.md
      - 快速开始demo:
          - zvision_nz_series/demo/index.md
          - demo1: zvision_nz_series/demo/demo1.md
          - demo2: zvision_nz_series/demo/demo2.md
      - 快速开始SLAM: zvision_nz_series/slam.md
  - 产品文档:
      - ZVISION NZ 系列: zvision_nz_series/index.md
      - NZ1:
          - 产品总览: zvision_nz_series/NZ1/index.md
          -  用户手册: zvision_nz_series/NZ1/cover.md
          -  阅读提示: zvision_nz_series/NZ1/00-reading-tips.md
          -  产品概述: zvision_nz_series/NZ1/01-产品概述.md
          -  硬件说明: zvision_nz_series/NZ1/02-硬件说明.md
          -  安装指南: zvision_nz_series/NZ1/03-安装指南.md
          -  电源与连接: zvision_nz_series/NZ1/04-电源与连接.md
          -  数据输出: zvision_nz_series/NZ1/05-数据输出.md
          -  SLAM 启动:
              -  FASTLIO2 使用说明: zvision_nz_series/NZ1/SLAM/01-FASTLIO2使用说明.md
              -  SuperLIO2 使用说明: zvision_nz_series/NZ1/SLAM/02-SuperLIO2使用说明.md
          -  建图与重定位API: zvision_nz_series/NZ1/06-建图与重定位API.md
          -  Ubuntu快速启动: zvision_nz_series/NZ1/07-NZ1-Ubuntu快速启动.md
          -  Windows快速启动: zvision_nz_series/NZ1/08-NZ1-Viewer-Windows快速启动.md
          -  固件升级: zvision_nz_series/NZ1/09-固件升级.md
          -  重定位使用说明: zvision_nz_series/NZ1/10-重定位使用说明.md
          -  重定位地图获取: zvision_nz_series/NZ1/11-重定位地图获取.md
          -  时间同步: zvision_nz_series/NZ1/12-时间同步.md
          -  维护与故障排除: zvision_nz_series/NZ1/13-维护与故障排除.md
          -  技术参数: zvision_nz_series/NZ1/14-技术参数.md
          -  常见问题FAQ: zvision_nz_series/NZ1/15-常见问题FAQ.md
          -  关注我们: zvision_nz_series/NZ1/关注我们.md
  - 配置说明: config.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
